name: Feature Request
description: Suggest a feature
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Include Phase 1 constraints if relevant.
